# Generated by Django 4.2.1 on 2023-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_contributor_project_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contributor",
            name="project_contributors",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="author_user_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="issue_id",
            new_name="issue",
        ),
        migrations.RenameField(
            model_name="contributor",
            old_name="project_id",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="contributor",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="assignee_user_id",
            new_name="assignee",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="author_user_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="project_id",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="author_user_id",
            new_name="author",
        ),
        migrations.AddConstraint(
            model_name="contributor",
            constraint=models.UniqueConstraint(
                fields=("user", "project"), name="project_contributors"
            ),
        ),
    ]
