# Generated by Django 4.2.1 on 2023-05-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_contributor_project_alter_contributor_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contributor",
            constraint=models.UniqueConstraint(
                fields=("user", "project"), name="project_contributor"
            ),
        ),
    ]
